const CORPUS = new Map([
  ["E100", {"code":"E100","names":"Curcumin (from turmeric)","type":"color (Yellow-orange)","status":"e u"}],
  ["E101", {"code":"E101","names":"Riboflavin (Vitamin B2), formerly called lactoflavin","type":"color (Yellow-orange)","status":"e u"}],
  ["E101a", {"code":"E101a","names":"Riboflavin-5'-Phosphate","type":"color (Yellow-orange)","status":"e"}],
  ["E102", {"code":"E102","names":"Tartrazine (FD&C Yellow 5)","type":"color (Lemon yellow)","status":"e u"}],
  ["E103", {"code":"E103","names":"Alkannin[11]","type":"color (Red-brown)","status":""}],
  ["E104", {"code":"E104","names":"Quinoline Yellow WS","type":"color (Dull or greenish yellow)","status":"e"}],
  ["E105", {"code":"E105","names":"Fast Yellow AB","type":"color (Yellow)","status":""}],
  ["E106", {"code":"E106","names":"Riboflavin-5-Sodium Phosphate","type":"color (Yellow)","status":""}],
  ["E107", {"code":"E107","names":"Yellow 2G","type":"color (Yellow)","status":""}],
  ["E110", {"code":"E110","names":"Sunset Yellow FCF (Orange Yellow S, FD&C Yellow 6)","type":"color (Yellow-orange)","status":"e u"}],
  ["E111", {"code":"E111","names":"Orange GGN","type":"color (Orange)","status":""}],
  ["E120", {"code":"E120","names":"Cochineal, Carminic acid, Carmine (Natural Red 4)","type":"color (Crimson)","status":"e u"}],
  ["E121", {"code":"E121","names":"Citrus Red 2","type":"color (Dark red)","status":""}],
  ["E122", {"code":"E122","names":"Carmoisine (azorubine)","type":"color (Red to maroon)","status":"e"}],
  ["E123", {"code":"E123","names":"Amaranth (FD&C Red 2)","type":"color (Dark red)","status":"e"}],
  ["E124", {"code":"E124","names":"Ponceau 4R (Cochineal Red A, Brilliant Scarlet 4R)","type":"color (Red)","status":"e"}],
  ["E125", {"code":"E125","names":"Ponceau SX, Scarlet GN","type":"color (Red)","status":""}],
  ["E126", {"code":"E126","names":"Ponceau 6R","type":"color (Red)","status":""}],
  ["E127", {"code":"E127","names":"Erythrosine (FD&C Red 3)","type":"color (Red)","status":"e u"}],
  ["E128", {"code":"E128","names":"Red 2G","type":"color (Red)","status":""}],
  ["E129", {"code":"E129","names":"Allura Red AC (FD&C Red 40)","type":"color (Red)","status":"e u"}],
  ["E130", {"code":"E130","names":"Indanthrene blue RS","type":"color (Blue)","status":""}],
  ["E131", {"code":"E131","names":"Patent Blue V","type":"color (Dark blue)","status":"e"}],
  ["E132", {"code":"E132","names":"Indigo carmine (indigotine, FD&C Blue 2)","type":"color (Indigo)","status":"e u"}],
  ["E133", {"code":"E133","names":"Brilliant Blue FCF (FD&C Blue 1)","type":"color (Reddish blue)","status":"e u"}],
  ["E140", {"code":"E140","names":"Chlorophylls and Chlorophyllins: (i) Chlorophylls (ii) Chlorophyllins","type":"color (Green)","status":"e"}],
  ["E141", {"code":"E141","names":"Copper complexes of chlorophylls and chlorophyllins (i) Copper complexes of chlorophylls (ii) Copper complexes of chlorophyllins","type":"color (Green)","status":"e u"}],
  ["E142", {"code":"E142","names":"Green S","type":"color (Green)","status":"e"}],
  ["E143", {"code":"E143","names":"Fast Green FCF (FD&C Green 3)","type":"color (Sea green)","status":"u"}],
  ["E150a", {"code":"E150a","names":"Plain caramel","type":"color (Brown)","status":"e u"}],
  ["E150b", {"code":"E150b","names":"Caustic sulphite caramel","type":"color (Brown)","status":"e u"}],
  ["E150c", {"code":"E150c","names":"Ammonia caramel","type":"color (Brown)","status":"e u"}],
  ["E150d", {"code":"E150d","names":"Sulphite ammonia caramel","type":"color (Brown)","status":"u"}],
  ["E151", {"code":"E151","names":"Black PN, Brilliant Black BN","type":"color (Black)","status":"e"}],
  ["E152", {"code":"E152","names":"Carbon black (hydrocarbon)","type":"color (Black)","status":""}],
  ["E153", {"code":"E153","names":"Vegetable carbon","type":"color (Black)","status":"e"}],
  ["E154", {"code":"E154","names":"Brown FK (kipper brown)","type":"color (Brown)","status":"e"}],
  ["E155", {"code":"E155","names":"Brown HT (chocolate brown HT)","type":"color (Brown)","status":"e"}],
  ["E160a", {"code":"E160a","names":"Alpha-carotene, Beta-carotene, Gamma-carotene","type":"color (Yellow-orange to brown)","status":"e"}],
  ["E160b", {"code":"E160b","names":"Annatto, bixin, norbixin","type":"color (Orange)","status":"e u"}],
  ["E160c", {"code":"E160c","names":"Paprika oleoresin, Capsanthin, capsorubin","type":"color (Red)","status":"e u"}],
  ["E160d", {"code":"E160d","names":"Lycopene","type":"color (Bright to deep red)","status":"e u"}],
  ["E160e", {"code":"E160e","names":"Beta-apo-8'-carotenal (C 30)","type":"color (Orange-red to yellow)","status":"e u"}],
  ["E160f", {"code":"E160f","names":"Ethyl ester of beta-apo-8'-carotenic acid (C 30)","type":"color (Orange-red to yellow)","status":"e"}],
  ["E161a", {"code":"E161a","names":"Flavoxanthin","type":"color (Golden-yellow and brownish)","status":""}],
  ["E161b", {"code":"E161b","names":"Lutein","type":"color (Orange-red to yellow)","status":"e"}],
  ["E161c", {"code":"E161c","names":"Cryptoxanthin","type":"color (Orange-red)","status":""}],
  ["E161d", {"code":"E161d","names":"Rubixanthin","type":"color (Orange-red)","status":""}],
  ["E161e", {"code":"E161e","names":"Violaxanthin","type":"color (Orange)","status":""}],
  ["E161f", {"code":"E161f","names":"Rhodoxanthin","type":"color (Purple)","status":""}],
  ["E161g", {"code":"E161g","names":"Canthaxanthin","type":"color (Violet)","status":"e u"}],
  ["E161h", {"code":"E161h","names":"Zeaxanthin","type":"color (Orange-red)","status":""}],
  ["E161i", {"code":"E161i","names":"Citranaxanthin","type":"color (Deep violet)","status":""}],
  ["E161j", {"code":"E161j","names":"Astaxanthin","type":"color (Red)","status":""}],
  ["E162", {"code":"E162","names":"Beetroot Red, Betanin","type":"color (Red)","status":"e u"}],
  ["E163", {"code":"E163","names":"Anthocyanins","type":"color (pH dependent, Red, green and purple ranges)","status":"e"}],
  ["E164", {"code":"E164","names":"Saffron","type":"color (Orange-red[colour?])","status":"u"}],
  ["E170", {"code":"E170","names":"Calcium carbonate, Chalk","type":"color (White)","status":"e"}],
  ["E171", {"code":"E171","names":"Titanium dioxide","type":"color (White)","status":"e u"}],
  ["E172", {"code":"E172","names":"Iron oxides and iron hydroxides","type":"color (Brown)","status":"e u"}],
  ["E173", {"code":"E173","names":"Aluminium","type":"color (Silver to grey)","status":"e"}],
  ["E174", {"code":"E174","names":"Silver","type":"color (Silver)","status":"e"}],
  ["E175", {"code":"E175","names":"Gold","type":"color (Gold)","status":"e"}],
  ["E180", {"code":"E180","names":"Pigment Rubine, Lithol Rubine BK","type":"color (Red)","status":"e"}],
  ["E181", {"code":"E181","names":"Tannin","type":"color (Brown)","status":""}],
  ["E182", {"code":"E182","names":"Orcein, Orchil","type":"color (Purple)","status":""}],
  ["E200", {"code":"E200","names":"Sorbic acid","type":"preservative","status":"e"}],
  ["E201", {"code":"E201","names":"Sodium sorbate","type":"preservative","status":""}],
  ["E202", {"code":"E202","names":"Potassium sorbate","type":"preservative","status":"e"}],
  ["E203", {"code":"E203","names":"Calcium sorbate","type":"preservative","status":"e"}],
  ["E209", {"code":"E209","names":"Heptyl p-hydroxybenzoate","type":"preservative","status":""}],
  ["E210", {"code":"E210","names":"Benzoic acid","type":"preservative","status":"e"}],
  ["E211", {"code":"E211","names":"Sodium benzoate","type":"preservative","status":"e"}],
  ["E212", {"code":"E212","names":"Potassium benzoate","type":"preservative","status":"e"}],
  ["E213", {"code":"E213","names":"Calcium benzoate","type":"preservative","status":"e"}],
  ["E214", {"code":"E214","names":"Ethylparaben (ethyl para-hydroxybenzoate)","type":"preservative","status":"e"}],
  ["E215", {"code":"E215","names":"Sodium ethyl para-hydroxybenzoate","type":"preservative","status":"e"}],
  ["E216", {"code":"E216","names":"Propylparaben (propyl para-hydroxybenzoate)","type":"preservative","status":""}],
  ["E217", {"code":"E217","names":"Sodium propyl para-hydroxybenzoate","type":"preservative","status":""}],
  ["E218", {"code":"E218","names":"Methylparaben (methyl para-hydroxybenzoate)","type":"preservative","status":"e"}],
  ["E219", {"code":"E219","names":"Sodium methyl para-hydroxybenzoate","type":"preservative","status":"e"}],
  ["E220", {"code":"E220","names":"Sulphur dioxide","type":"preservative","status":"e"}],
  ["E221", {"code":"E221","names":"Sodium sulphite","type":"preservative","status":"e"}],
  ["E222", {"code":"E222","names":"Sodium bisulphite (sodium hydrogen sulphite)","type":"preservative","status":"e"}],
  ["E223", {"code":"E223","names":"Sodium metabisulphite","type":"preservative","status":"e"}],
  ["E224", {"code":"E224","names":"Potassium metabisulphite","type":"preservative","status":"e"}],
  ["E225", {"code":"E225","names":"Potassium sulphite","type":"preservative","status":""}],
  ["E226", {"code":"E226","names":"Calcium sulphite","type":"preservative","status":"e"}],
  ["E227", {"code":"E227","names":"Calcium hydrogen sulphite (preservative)","type":"firming agent","status":"e"}],
  ["E228", {"code":"E228","names":"Potassium hydrogen sulphite","type":"preservative","status":"e"}],
  ["E230", {"code":"E230","names":"Biphenyl, diphenyl","type":"preservative","status":"e"}],
  ["E231", {"code":"E231","names":"Orthophenyl phenol","type":"preservative","status":"e"}],
  ["E232", {"code":"E232","names":"Sodium orthophenyl phenol","type":"preservative","status":"e"}],
  ["E233", {"code":"E233","names":"Thiabendazole","type":"preservative","status":""}],
  ["E234", {"code":"E234","names":"Nisin","type":"preservative","status":"e"}],
  ["E235", {"code":"E235","names":"Natamycin, Pimaracin","type":"preservative","status":"e"}],
  ["E236", {"code":"E236","names":"Formic acid","type":"preservative","status":""}],
  ["E237", {"code":"E237","names":"Sodium formate","type":"preservative","status":""}],
  ["E238", {"code":"E238","names":"Calcium formate","type":"preservative","status":""}],
  ["E239", {"code":"E239","names":"Hexamine (hexamethylene tetramine)","type":"preservative","status":"e"}],
  ["E240", {"code":"E240","names":"Formaldehyde","type":"preservative","status":""}],
  ["E242", {"code":"E242","names":"Dimethyl dicarbonate","type":"preservative","status":"e"}],
  ["E249", {"code":"E249","names":"Potassium nitrite","type":"preservative","status":"e"}],
  ["E250", {"code":"E250","names":"Sodium nitrite","type":"preservative","status":"e"}],
  ["E251", {"code":"E251","names":"Sodium nitrate (Chile saltpeter)","type":"preservative","status":"e"}],
  ["E252", {"code":"E252","names":"Potassium nitrate (Saltpetre)","type":"preservative","status":"e"}],
  ["E260", {"code":"E260","names":"Acetic acid (preservative)","type":"acidity regulator","status":"e"}],
  ["E261", {"code":"E261","names":"Potassium acetate (preservative)","type":"acidity regulator","status":"e"}],
  ["E262", {"code":"E262","names":"Sodium acetates (i) Sodium acetate (ii) Sodium diacetate (sodium hydrogen acetate)","type":"preservative, acidity regulator","status":"e"}],
  ["E263", {"code":"E263","names":"Calcium acetate (preservative)","type":"acidity regulator","status":"e"}],
  ["E264", {"code":"E264","names":"Ammonium acetate","type":"preservative","status":""}],
  ["E265", {"code":"E265","names":"Dehydroacetic acid","type":"preservative","status":""}],
  ["E266", {"code":"E266","names":"Sodium dehydroacetate","type":"preservative","status":""}],
  ["E270", {"code":"E270","names":"Lactic acid (preservative)","type":"antioxidant","status":"e"}],
  ["E280", {"code":"E280","names":"Propionic acid","type":"preservative","status":"e"}],
  ["E281", {"code":"E281","names":"Sodium propionate","type":"preservative","status":"e"}],
  ["E282", {"code":"E282","names":"Calcium propionate","type":"preservative","status":"e"}],
  ["E283", {"code":"E283","names":"Potassium propionate","type":"preservative","status":"e"}],
  ["E284", {"code":"E284","names":"Boric acid","type":"preservative","status":"e"}],
  ["E285", {"code":"E285","names":"Sodium tetraborate (borax)","type":"preservative","status":"e"}],
  ["E290", {"code":"E290","names":"Carbon dioxide","type":"acidity regulator","status":"e"}],
  ["E296", {"code":"E296","names":"Malic acid (acid)","type":"acidity regulator","status":"e"}],
  ["E297", {"code":"E297","names":"Fumaric acid","type":"acidity regulator","status":"e"}],
  ["E300", {"code":"E300","names":"Ascorbic acid (Vitamin C)","type":"antioxidant","status":"e"}],
  ["E301", {"code":"E301","names":"Sodium ascorbate","type":"antioxidant","status":"e"}],
  ["E302", {"code":"E302","names":"Calcium ascorbate","type":"antioxidant","status":"e"}],
  ["E303", {"code":"E303","names":"Potassium ascorbate","type":"antioxidant","status":""}],
  ["E304", {"code":"E304","names":"Fatty acid esters of ascorbic acid (Ascorbyl palmitate)","type":"antioxidant","status":"e"}],
  ["E305", {"code":"E305","names":"Ascorbyl stearate","type":"antioxidant","status":""}],
  ["E306", {"code":"E306","names":"Tocopherols (Vitamin E, natural)","type":"antioxidant","status":"e"}],
  ["E307", {"code":"E307","names":"Alpha-Tocopherol (synthetic)","type":"antioxidant","status":"e"}],
  ["E308", {"code":"E308","names":"Gamma-Tocopherol (synthetic)","type":"antioxidant","status":"e"}],
  ["E309", {"code":"E309","names":"Delta-Tocopherol (synthetic)","type":"antioxidant","status":"e"}],
  ["E310", {"code":"E310","names":"Propyl gallate","type":"antioxidant","status":"e"}],
  ["E311", {"code":"E311","names":"Octyl gallate","type":"antioxidant","status":"e"}],
  ["E312", {"code":"E312","names":"Dodecyl gallate","type":"antioxidant","status":"e"}],
  ["E313", {"code":"E313","names":"Ethyl gallate","type":"antioxidant","status":""}],
  ["E314", {"code":"E314","names":"Guaiac resin","type":"antioxidant","status":""}],
  ["E315", {"code":"E315","names":"Erythorbic acid","type":"antioxidant","status":"e"}],
  ["E316", {"code":"E316","names":"Sodium erythorbate","type":"antioxidant","status":"e"}],
  ["E317", {"code":"E317","names":"Erythorbin acid","type":"antioxidant","status":""}],
  ["E318", {"code":"E318","names":"Sodium erythorbin","type":"antioxidant","status":""}],
  ["E319", {"code":"E319","names":"tert-Butylhydroquinone (TBHQ)","type":"antioxidant","status":"e"}],
  ["E320", {"code":"E320","names":"Butylated hydroxyanisole (BHA)","type":"antioxidant","status":"e"}],
  ["E321", {"code":"E321","names":"Butylated hydroxytoluene (BHT)","type":"antioxidant","status":"e"}],
  ["E322", {"code":"E322","names":"Lecithin","type":"emulsifier","status":"e"}],
  ["E323", {"code":"E323","names":"Anoxomer","type":"antioxidant","status":""}],
  ["E324", {"code":"E324","names":"Ethoxyquin","type":"antioxidant","status":""}],
  ["E325", {"code":"E325","names":"Sodium lactate","type":"acidity regulator","status":"e"}],
  ["E326", {"code":"E326","names":"Potassium lactate (antioxidant)","type":"acidity regulator","status":"e"}],
  ["E327", {"code":"E327","names":"Calcium lactate","type":"acidity regulator","status":"e"}],
  ["E328", {"code":"E328","names":"Ammonium lactate","type":"acidity regulator","status":""}],
  ["E329", {"code":"E329","names":"Magnesium lactate","type":"acidity regulator","status":""}],
  ["E330", {"code":"E330","names":"Citric acid","type":"acid, acidity regulator","status":"e"}],
  ["E331", {"code":"E331","names":"Sodium citrates (i) Monosodium citrate (ii) Disodium citrate (iii) Sodium citrate (trisodium citrate)","type":"acidity regulator","status":"e"}],
  ["E332", {"code":"E332","names":"Potassium citrates (i) Monopotassium citrate (ii) Potassium citrate (tripotassium citrate)","type":"acidity regulator","status":"e"}],
  ["E333", {"code":"E333","names":"Calcium citrates (i) Monocalcium citrate (ii) Dicalcium citrate (iii) Calcium citrate (tricalcium citrate)","type":"acidity regulator, firming agent, sequestrant","status":"e"}],
  ["E334", {"code":"E334","names":"Tartaric acid (L(+)-)","type":"(acid)","status":"e"}],
  ["E335", {"code":"E335","names":"Sodium tartrates (i) Monosodium tartrate (ii), Disodium tartrate","type":"acidity regulator","status":"e"}],
  ["E336", {"code":"E336","names":"Potassium tartrates (i) Monopotassium tartrate (cream of tartar) (ii) Dipotassium tartrate","type":"acidity regulator","status":"e"}],
  ["E337", {"code":"E337","names":"Sodium potassium tartrate","type":"acidity regulator","status":"e"}],
  ["E338", {"code":"E338","names":"Orthophosphoric acid","type":"acid","status":"e"}],
  ["E339", {"code":"E339","names":"Sodium phosphates (i) Monosodium phosphate (ii) Disodium phosphate (iii) Trisodium phosphate","type":"antioxidant","status":"e"}],
  ["E340", {"code":"E340","names":"Potassium phosphates (i) Monopotassium phosphate (ii) Dipotassium phosphate (iii) Tripotassium phosphate","type":"antioxidant","status":"e"}],
  ["E341", {"code":"E341","names":"Calcium phosphates (i) Monocalcium phosphate (ii) Dicalcium phosphate (iii) Tricalcium phosphate","type":"anti-caking agent, firming agent","status":"e"}],
  ["E342", {"code":"E342","names":"Ammonium phosphates: (i) monoammonium phosphate (ii) diammonium phosphate","type":"","status":""}],
  ["E343", {"code":"E343","names":"Magnesium phosphates (i) monomagnesium phosphate (ii) Dimagnesium phosphate","type":"anti-caking agent","status":"e"}],
  ["E344", {"code":"E344","names":"Lecitin citrate","type":"acidity regulator","status":""}],
  ["E345", {"code":"E345","names":"Magnesium citrate","type":"acidity regulator","status":""}],
  ["E349", {"code":"E349","names":"Ammonium malate","type":"acidity regulator","status":""}],
  ["E350", {"code":"E350","names":"Sodium malates (i) Sodium malate (ii) Sodium hydrogen malate","type":"acidity regulator","status":"e"}],
  ["E351", {"code":"E351","names":"Potassium malate","type":"acidity regulator","status":"e"}],
  ["E352", {"code":"E352","names":"Calcium malates (i) Calcium malate (ii) Calcium hydrogen malate","type":"acidity regulator","status":"e"}],
  ["E353", {"code":"E353","names":"Metatartaric acid","type":"emulsifier","status":"e"}],
  ["E354", {"code":"E354","names":"Calcium tartrate","type":"emulsifier","status":"e"}],
  ["E355", {"code":"E355","names":"Adipic acid","type":"acidity regulator","status":"e"}],
  ["E356", {"code":"E356","names":"Sodium adipate","type":"acidity regulator","status":"e"}],
  ["E357", {"code":"E357","names":"Potassium adipate","type":"acidity regulator","status":"e"}],
  ["E359", {"code":"E359","names":"Ammonium adipate","type":"acidity regulator","status":""}],
  ["E363", {"code":"E363","names":"Succinic acid","type":"acidity regulator","status":"e"}],
  ["E365", {"code":"E365","names":"Sodium fumarate","type":"acidity regulator","status":""}],
  ["E366", {"code":"E366","names":"Potassium fumarate","type":"acidity regulator","status":""}],
  ["E367", {"code":"E367","names":"Calcium fumarate","type":"acidity regulator","status":""}],
  ["E368", {"code":"E368","names":"Ammonium fumarate","type":"acidity regulator","status":""}],
  ["E370", {"code":"E370","names":"1,4-Heptonolactone","type":"acidity regulator","status":""}],
  ["E380", {"code":"E380","names":"Triammonium citrate","type":"acidity regulator","status":"e"}],
  ["E381", {"code":"E381","names":"Ammonium ferric citrate","type":"acidity regulator","status":""}],
  ["E383", {"code":"E383","names":"Calcium glycerylphosphate","type":"acidity regulator","status":""}],
  ["E384", {"code":"E384","names":"Isopropyl citrate","type":"acidity regulator","status":""}],
  ["E385", {"code":"E385","names":"Calcium disodium ethylene diamine tetraacetate, (Calcium disodium EDTA)","type":"sequestrant","status":"e"}],
  ["E386", {"code":"E386","names":"Disodium ethylene diamine tetraacetate (Disodium EDTA)","type":"sequestrant","status":""}],
  ["E387", {"code":"E387","names":"Oxystearin","type":"stabiliser","status":""}],
  ["E388", {"code":"E388","names":"Thiodipropionic acid","type":"","status":""}],
  ["E389", {"code":"E389","names":"Dilauryl thiodipropionate","type":"","status":""}],
  ["E390", {"code":"E390","names":"Distearyl thiodipropionate","type":"","status":""}],
  ["E391", {"code":"E391","names":"Phytic acid","type":"","status":""}],
  ["E392", {"code":"E392","names":"Extracts of rosemary","type":"","status":"e"}],
  ["E399", {"code":"E399","names":"Calcium lactobionate","type":"","status":""}],
  ["E400", {"code":"E400","names":"Alginic acid (thickener) (stabiliser) (gelling agent)","type":"emulsifier","status":"e"}],
  ["E401", {"code":"E401","names":"Sodium alginate (thickener) (stabiliser) (gelling agent)","type":"emulsifier","status":"e"}],
  ["E402", {"code":"E402","names":"Potassium alginate (thickener) (stabiliser) (gelling agent)","type":"emulsifier","status":"e"}],
  ["E403", {"code":"E403","names":"Ammonium alginate (thickener) (stabiliser)","type":"emulsifier","status":"e"}],
  ["E404", {"code":"E404","names":"Calcium alginate (thickener) (stabiliser) (gelling agent)","type":"emulsifier","status":"e"}],
  ["E405", {"code":"E405","names":"Propane-1,2-diol alginate (Propylene glycol alginate) (thickener) (stabiliser)","type":"emulsifier","status":"e"}],
  ["E406", {"code":"E406","names":"Agar (thickener) (gelling agent)","type":"stabiliser","status":"e"}],
  ["E407", {"code":"E407","names":"Carrageenan (thickener) (stabiliser) (gelling agent)","type":"emulsifier","status":"e"}],
  ["E407a", {"code":"E407a","names":"Processed eucheuma seaweed (thickener) (stabiliser) (gelling agent)","type":"emulsifier","status":"e"}],
  ["E408", {"code":"E408","names":"Bakers yeast glycan","type":"","status":""}],
  ["E409", {"code":"E409","names":"Arabinogalactan","type":"","status":""}],
  ["E410", {"code":"E410","names":"Locust bean gum (Carob gum) (thickener) (stabiliser) (gelling agent)","type":"emulsifier","status":"e"}],
  ["E411", {"code":"E411","names":"Oat gum (thickener)","type":"stabiliser","status":""}],
  ["E412", {"code":"E412","names":"Guar gum (thickener)","type":"stabiliser","status":"e"}],
  ["E413", {"code":"E413","names":"Tragacanth (thickener) (stabiliser)","type":"emulsifier","status":"e"}],
  ["E414", {"code":"E414","names":"Acacia gum (gum arabic) (thickener) (stabiliser)","type":"emulsifier","status":"e"}],
  ["E415", {"code":"E415","names":"Xanthan gum (thickener)","type":"stabiliser","status":"e"}],
  ["E416", {"code":"E416","names":"Karaya gum (thickener) (stabiliser)","type":"emulsifier","status":"e"}],
  ["E417", {"code":"E417","names":"Tara gum (thickener)","type":"stabiliser","status":"e"}],
  ["E418", {"code":"E418","names":"Gellan gum (thickener) (stabiliser)","type":"emulsifier","status":"e"}],
  ["E419", {"code":"E419","names":"Gum ghatti (thickener) (stabiliser)","type":"emulsifier","status":""}],
  ["E420", {"code":"E420","names":"Sorbitol (i) Sorbitol (ii) Sorbitol syrup (emulsifier) (sweetener)","type":"humectant","status":"e"}],
  ["E421", {"code":"E421","names":"Mannitol (anti-caking agent)","type":"sweetener","status":"e"}],
  ["E422", {"code":"E422","names":"Glycerol (emulsifier)","type":"sweetener","status":"e"}],
  ["E424", {"code":"E424","names":"Curdlan","type":"gelling agent","status":""}],
  ["E425", {"code":"E425","names":"Konjac (i) Konjac gum (ii) Konjac glucomannane","type":"emulsifier","status":"e"}],
  ["E426", {"code":"E426","names":"Soybean hemicellulose","type":"","status":"e"}],
  ["E427", {"code":"E427","names":"Cassia gum","type":"","status":"e"}],
  ["E429", {"code":"E429","names":"Peptones","type":"","status":""}],
  ["E430", {"code":"E430","names":"Polyoxyethene (8) stearate (emulsifier)","type":"stabiliser","status":""}],
  ["E431", {"code":"E431","names":"Polyoxyethene (40) stearate","type":"emulsifier","status":"e"}],
  ["E432", {"code":"E432","names":"Polyoxyethene (20) sorbitan monolaurate (polysorbate 20)","type":"emulsifier","status":"e"}],
  ["E433", {"code":"E433","names":"Polyoxyethene (20) sorbitan monooleate (polysorbate 80)","type":"emulsifier","status":"e"}],
  ["E434", {"code":"E434","names":"Polyoxyethene (20) sorbitan monopalmitate (polysorbate 40)","type":"emulsifier","status":"e"}],
  ["E435", {"code":"E435","names":"Polyoxyethene (20) sorbitan monostearate (polysorbate 60)","type":"emulsifier","status":"e"}],
  ["E436", {"code":"E436","names":"Polyoxyethene (20) sorbitan tristearate (polysorbate 65)","type":"emulsifier","status":"e"}],
  ["E440", {"code":"E440","names":"Pectins (i) pectin (ii) amidated pectin","type":"emulsifier","status":"e"}],
  ["E441", {"code":"E441","names":"Gelatine (emulsifier)","type":"gelling agent","status":""}],
  ["E442", {"code":"E442","names":"Ammonium phosphatides","type":"emulsifier","status":"e"}],
  ["E443", {"code":"E443","names":"Brominated vegetable oil","type":"emulsifier","status":""}],
  ["E444", {"code":"E444","names":"Sucrose acetate isobutyrate","type":"emulsifier","status":""}],
  ["E445", {"code":"E445","names":"Glycerol esters of wood rosins","type":"emulsifier","status":"e"}],
  ["E446", {"code":"E446","names":"Succistearin","type":"","status":""}],
  ["E450", {"code":"E450","names":"Diphosphates (i) Disodium diphosphate (ii) Trisodium diphosphate (iii) Tetrasodium diphosphate (iv) Dipotassium diphosphate (v) Tetrapotassium diphosphate (vi) Dicalcium diphosphate (vii) Calcium dihydrogen diphosphate","type":"emulsifier","status":"e"}],
  ["E451", {"code":"E451","names":"Triphosphates (i) Sodium triphosphate (pentasodium triphosphate) (ii) Pentapotassium triphosphate","type":"emulsifier","status":"e"}],
  ["E452", {"code":"E452","names":"Polyphosphates (i) Sodium polyphosphates (ii) Potassium polyphosphates (iii) Sodium calcium polyphosphate (iv) Calcium polyphosphates (v) Ammonium polyphosphate","type":"emulsifier","status":"e"}],
  ["E459", {"code":"E459","names":"Beta-cyclodextrin","type":"emulsifier","status":"e"}],
  ["E460", {"code":"E460","names":"Cellulose (i) Microcrystalline cellulose (ii) Powdered cellulose","type":"emulsifier","status":"e"}],
  ["E461", {"code":"E461","names":"Methyl cellulose","type":"emulsifier","status":"e"}],
  ["E462", {"code":"E462","names":"Ethyl cellulose","type":"emulsifier","status":"e"}],
  ["E463", {"code":"E463","names":"Hydroxypropyl cellulose","type":"emulsifier","status":"e"}],
  ["E464", {"code":"E464","names":"Hypromellose (hydroxypropyl methylcellulose)","type":"emulsifier","status":"e"}],
  ["E465", {"code":"E465","names":"Ethyl methyl cellulose","type":"emulsifier","status":"e"}],
  ["E466", {"code":"E466","names":"Carboxymethyl cellulose, Sodium carboxymethyl cellulose","type":"emulsifier","status":"e"}],
  ["E467", {"code":"E467","names":"Ethyl hydroxyethyl cellulose","type":"","status":""}],
  ["E468", {"code":"E468","names":"Crosslinked sodium carboxymethyl cellulose (Croscarmellose)","type":"emulsifier","status":"e"}],
  ["E469", {"code":"E469","names":"Enzymically hydrolysed carboxymethylcellulose","type":"emulsifier","status":"e"}],
  ["E470a", {"code":"E470a","names":"Sodium, potassium and calcium salts of fatty acids (emulsifier)","type":"anti-caking agent","status":"e"}],
  ["E470b", {"code":"E470b","names":"Magnesium salts of fatty acids (emulsifier)","type":"anti-caking agent","status":"e"}],
  ["E471", {"code":"E471","names":"Mono- and diglycerides of fatty acids (glyceryl monostearate, glyceryl distearate)","type":"emulsifier","status":"e"}],
  ["E472a", {"code":"E472a","names":"Acetic acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"e"}],
  ["E472b", {"code":"E472b","names":"Lactic acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"e"}],
  ["E472c", {"code":"E472c","names":"Citric acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"e"}],
  ["E472d", {"code":"E472d","names":"Tartaric acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"e"}],
  ["E472e", {"code":"E472e","names":"Mono- and diacetyl tartaric acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"e"}],
  ["E472f", {"code":"E472f","names":"Mixed acetic and tartaric acid esters of mono- and diglycerides of fatty acids","type":"emulsifier","status":"e"}],
  ["E472g", {"code":"E472g","names":"Succinylated monoglycerides","type":"emulsifier","status":""}],
  ["E473", {"code":"E473","names":"Sucrose esters of fatty acids","type":"emulsifier","status":"e"}],
  ["E474", {"code":"E474","names":"Sucroglycerides","type":"emulsifier","status":"e"}],
  ["E475", {"code":"E475","names":"Polyglycerol esters of fatty acids","type":"emulsifier","status":"e"}],
  ["E476", {"code":"E476","names":"Polyglycerol polyricinoleate","type":"emulsifier","status":"e"}],
  ["E477", {"code":"E477","names":"Propane-1,2-diol esters of fatty acids, propylene glycol esters of fatty acids","type":"emulsifier","status":"e"}],
  ["E478", {"code":"E478","names":"Lactylated fatty acid esters of glycerol and propane-1","type":"emulsifier","status":""}],
  ["E479b", {"code":"E479b","names":"Thermally oxidized soya bean oil interacted with mono- and diglycerides of fatty acids","type":"emulsifier","status":"e"}],
  ["E480", {"code":"E480","names":"Dioctyl sodium sulphosuccinate","type":"emulsifier","status":""}],
  ["E481", {"code":"E481","names":"Sodium stearoyl-2-lactylate","type":"emulsifier","status":"e"}],
  ["E482", {"code":"E482","names":"Calcium stearoyl-2-lactylate","type":"emulsifier","status":"e"}],
  ["E483", {"code":"E483","names":"Stearyl tartrate","type":"emulsifier","status":"e"}],
  ["E484", {"code":"E484","names":"Stearyl citrate","type":"emulsifier","status":""}],
  ["E485", {"code":"E485","names":"Sodium stearoyl fumarate","type":"emulsifier","status":""}],
  ["E486", {"code":"E486","names":"Calcium stearoyl fumarate","type":"emulsifier","status":""}],
  ["E487", {"code":"E487","names":"Sodium laurylsulphate","type":"emulsifier","status":""}],
  ["E488", {"code":"E488","names":"Ethoxylated Mono- and Di-Glycerides","type":"emulsifier","status":""}],
  ["E489", {"code":"E489","names":"Methyl glucoside-coconut oil ester","type":"emulsifier","status":""}],
  ["E490", {"code":"E490","names":"Propane-1,2-diol","type":"","status":""}],
  ["E491", {"code":"E491","names":"Sorbitan monostearate","type":"emulsifier","status":"e"}],
  ["E492", {"code":"E492","names":"Sorbitan tristearate","type":"emulsifier","status":"e"}],
  ["E493", {"code":"E493","names":"Sorbitan monolaurate","type":"emulsifier","status":"e"}],
  ["E494", {"code":"E494","names":"Sorbitan monooleate","type":"emulsifier","status":"e"}],
  ["E495", {"code":"E495","names":"Sorbitan monopalmitate","type":"emulsifier","status":"e"}],
  ["E496", {"code":"E496","names":"Sorbitan trioleate","type":"emulsifier","status":""}],
  ["E497", {"code":"E497","names":"Polyoxypropylene-polyoxyethylene polymers","type":"","status":""}],
  ["E498", {"code":"E498","names":"Partial polyglycerol esters of polycondensed fatty acids of castor oil","type":"","status":""}],
  ["E500", {"code":"E500","names":"Sodium carbonates (i) Sodium carbonate (ii) Sodium bicarbonate (Sodium hydrogen carbonate) (iii) Sodium sesquicarbonate (acidity regulator)","type":"raising agent","status":"e"}],
  ["E501", {"code":"E501","names":"Potassium carbonates (i) Potassium carbonate (ii) Potassium bicarbonate (Potassium hydrogen carbonate)","type":"acidity regulator","status":"e"}],
  ["E503", {"code":"E503","names":"Ammonium carbonates (i) Ammonium carbonate (ii) Ammonium bicarbonate (Ammonium hydrogen carbonate)","type":"acidity regulator","status":"e"}],
  ["E504", {"code":"E504","names":"Magnesium carbonates (i) Magnesium carbonate (ii) Magnesium bicarbonate Magnesium hydrogen carbonate","type":"acidity regulator, anti-caking agent","status":"e"}],
  ["E505", {"code":"E505","names":"Ferrous carbonate","type":"acidity regulator","status":""}],
  ["E507", {"code":"E507","names":"Hydrochloric acid","type":"acid","status":"e"}],
  ["E508", {"code":"E508","names":"Potassium chloride (gelling agent)","type":"seasoning","status":"e"}],
  ["E509", {"code":"E509","names":"Calcium chloride (sequestrant)","type":"firming agent","status":"e"}],
  ["E510", {"code":"E510","names":"Ammonium chloride, ammonia solution (acidity regulator)","type":"improving agent","status":""}],
  ["E511", {"code":"E511","names":"Magnesium chloride","type":"firming agent","status":"e"}],
  ["E512", {"code":"E512","names":"Stannous chloride","type":"antioxidant","status":"e"}],
  ["E513", {"code":"E513","names":"Sulphuric acid","type":"acid","status":"e"}],
  ["E514", {"code":"E514","names":"Sodium sulphates (i) Sodium sulphate (ii)","type":"acid","status":"e"}],
  ["E515", {"code":"E515","names":"Potassium Sulphates (i) Potassium Sulphate (ii)","type":"","status":"e"}],
  ["E516", {"code":"E516","names":"Calcium sulphate","type":"","status":"e"}],
  ["E517", {"code":"E517","names":"Ammonium sulphate","type":"acidity regulator","status":"e"}],
  ["E518", {"code":"E518","names":"Magnesium sulphate (Epsom salts), (acidity regulator)","type":"firming agent","status":""}],
  ["E519", {"code":"E519","names":"Copper(II) sulphate","type":"preservative","status":""}],
  ["E520", {"code":"E520","names":"Aluminium sulphate","type":"firming agent","status":"e"}],
  ["E521", {"code":"E521","names":"Aluminium sodium sulphate","type":"firming agent","status":"e"}],
  ["E522", {"code":"E522","names":"Aluminium potassium sulphate","type":"acidity regulator","status":"e"}],
  ["E523", {"code":"E523","names":"Aluminium ammonium sulphate","type":"acidity regulator","status":"e"}],
  ["E524", {"code":"E524","names":"Sodium hydroxide","type":"acidity regulator","status":"e"}],
  ["E525", {"code":"E525","names":"Potassium hydroxide","type":"acidity regulator","status":"e"}],
  ["E526", {"code":"E526","names":"Calcium hydroxide (acidity regulator)","type":"firming agent","status":"e"}],
  ["E527", {"code":"E527","names":"Ammonium hydroxide","type":"acidity regulator","status":"e"}],
  ["E528", {"code":"E528","names":"Magnesium hydroxide","type":"acidity regulator","status":"e"}],
  ["E529", {"code":"E529","names":"Calcium oxide (acidity regulator)","type":"improving agent","status":"e"}],
  ["E530", {"code":"E530","names":"Magnesium oxide (acidity regulator)","type":"anti-caking agent","status":"e"}],
  ["E535", {"code":"E535","names":"Sodium ferrocyanide (acidity regulator)","type":"anti-caking agent","status":"e"}],
  ["E536", {"code":"E536","names":"Potassium ferrocyanide","type":"anti-caking agent","status":"e"}],
  ["E537", {"code":"E537","names":"Ferrous hexacyanomanganate","type":"anti-caking agent","status":""}],
  ["E538", {"code":"E538","names":"Calcium ferrocyanide","type":"anti-caking agent","status":"e"}],
  ["E539", {"code":"E539","names":"Sodium thiosulphate","type":"antioxidant","status":""}],
  ["E540", {"code":"E540","names":"Dicalcium diphosphate (acidity regulator)","type":"emulsifier","status":""}],
  ["E541", {"code":"E541","names":"Sodium aluminium phosphate (i) Acidic (ii) Basic","type":"emulsifier","status":"e"}],
  ["E542", {"code":"E542","names":"Bone phosphate (Essentiale Calcium Phosphate, Tribasic)","type":"anti-caking agent","status":""}],
  ["E543", {"code":"E543","names":"Calcium sodium polyphosphate","type":"emulsifier","status":""}],
  ["E544", {"code":"E544","names":"Calcium polyphosphate","type":"emulsifier","status":""}],
  ["E545", {"code":"E545","names":"Ammonium polyphosphate","type":"emulsifier","status":""}],
  ["E550", {"code":"E550","names":"Sodium Silicates (i) Sodium silicate (ii) Sodium metasilicate","type":"anti-caking agent","status":""}],
  ["E551", {"code":"E551","names":"Silicon dioxide (Silica)","type":"anti-caking agent","status":"e"}],
  ["E552", {"code":"E552","names":"Calcium silicate","type":"anti-caking agent","status":"e"}],
  ["E553a", {"code":"E553a","names":"(i) Magnesium silicate (ii) Magnesium trisilicate","type":"anti-caking agent","status":"e"}],
  ["E553b", {"code":"E553b","names":"Talc","type":"anti-caking agent","status":"e"}],
  ["E554", {"code":"E554","names":"Sodium aluminosilicate (sodium aluminium silicate)","type":"anti-caking agent","status":"e"}],
  ["E555", {"code":"E555","names":"Potassium aluminium silicate","type":"anti-caking agent","status":"e"}],
  ["E556", {"code":"E556","names":"Calcium aluminosilicate (calcium aluminium silicate)","type":"anti-caking agent","status":"e"}],
  ["E557", {"code":"E557","names":"Zinc silicate","type":"anti-caking agent","status":""}],
  ["E558", {"code":"E558","names":"Bentonite","type":"anti-caking agent","status":""}],
  ["E559", {"code":"E559","names":"Aluminium silicate (Kaolin)","type":"anti-caking agent","status":"e"}],
  ["E560", {"code":"E560","names":"Potassium silicate","type":"anti-caking agent","status":""}],
  ["E561", {"code":"E561","names":"Vermiculite","type":"","status":""}],
  ["E562", {"code":"E562","names":"Sepiolite","type":"","status":""}],
  ["E563", {"code":"E563","names":"Sepiolitic clay","type":"","status":""}],
  ["E565", {"code":"E565","names":"Lignosulphonates","type":"","status":""}],
  ["E566", {"code":"E566","names":"Natrolite-phonolite","type":"","status":""}],
  ["E570", {"code":"E570","names":"Fatty acids","type":"anti-caking agent","status":"e"}],
  ["E572", {"code":"E572","names":"Magnesium stearate, calcium stearate (emulsifier)","type":"anti-caking agent","status":""}],
  ["E574", {"code":"E574","names":"Gluconic acid","type":"acidity regulator","status":"e"}],
  ["E575", {"code":"E575","names":"Glucono delta-lactone (acidity regulator)","type":"sequestrant","status":"e"}],
  ["E576", {"code":"E576","names":"Sodium gluconate","type":"sequestrant","status":"e"}],
  ["E577", {"code":"E577","names":"Potassium gluconate","type":"sequestrant","status":"e"}],
  ["E578", {"code":"E578","names":"Calcium gluconate","type":"firming agent","status":"e"}],
  ["E579", {"code":"E579","names":"Ferrous gluconate","type":"food colouring","status":"e"}],
  ["E580", {"code":"E580","names":"Magnesium gluconate","type":"","status":""}],
  ["E585", {"code":"E585","names":"Ferrous lactate","type":"food colouring","status":"e"}],
  ["E586", {"code":"E586","names":"4-Hexylresorcinol","type":"antioxidant","status":"e"}],
  ["E598", {"code":"E598","names":"Synthetic calcium aluminates","type":"","status":""}],
  ["E599", {"code":"E599","names":"Perlite","type":"","status":""}],
  ["E620", {"code":"E620","names":"Glutamic acid","type":"flavour enhancer","status":"e"}],
  ["E621", {"code":"E621","names":"Monosodium glutamate (MSG)","type":"flavour enhancer","status":"e"}],
  ["E622", {"code":"E622","names":"Monopotassium glutamate","type":"flavour enhancer","status":"e"}],
  ["E623", {"code":"E623","names":"Calcium diglutamate","type":"flavour enhancer","status":"e"}],
  ["E624", {"code":"E624","names":"Monoammonium glutamate","type":"flavour enhancer","status":"e"}],
  ["E625", {"code":"E625","names":"Magnesium diglutamate","type":"flavour enhancer","status":"e"}],
  ["E626", {"code":"E626","names":"Guanylic acid","type":"flavour enhancer","status":"e"}],
  ["E627", {"code":"E627","names":"Disodium guanylate, sodium guanylate","type":"flavour enhancer","status":"e"}],
  ["E628", {"code":"E628","names":"Dipotassium guanylate","type":"flavour enhancer","status":"e"}],
  ["E629", {"code":"E629","names":"Calcium guanylate","type":"flavour enhancer","status":"e"}],
  ["E630", {"code":"E630","names":"Inosinic acid","type":"flavour enhancer","status":"e"}],
  ["E631", {"code":"E631","names":"Disodium inosinate","type":"flavour enhancer","status":"e"}],
  ["E632", {"code":"E632","names":"Dipotassium inosinate","type":"flavour enhancer","status":"e"}],
  ["E633", {"code":"E633","names":"Calcium inosinate","type":"flavour enhancer","status":"e"}],
  ["E634", {"code":"E634","names":"Calcium 5'-ribonucleotides","type":"flavour enhancer","status":"e"}],
  ["E635", {"code":"E635","names":"Disodium 5'-ribonucleotides","type":"flavour enhancer","status":"e"}],
  ["E640", {"code":"E640","names":"Glycine and its sodium salt","type":"flavour enhancer","status":"e"}],
  ["E650", {"code":"E650","names":"Zinc acetate","type":"flavour enhancer","status":"e"}],
  ["E701", {"code":"E701","names":"Tetracyclines","type":"antibiotic","status":""}],
  ["E702", {"code":"E702","names":"Chlortetracycline","type":"antibiotic","status":""}],
  ["E703", {"code":"E703","names":"Oxytetracycline","type":"antibiotic","status":""}],
  ["E704", {"code":"E704","names":"Oleandomycin","type":"antibiotic","status":""}],
  ["E705", {"code":"E705","names":"Penicillin G potassium","type":"antibiotic","status":""}],
  ["E706", {"code":"E706","names":"Penicillin G sodium","type":"antibiotic","status":""}],
  ["E707", {"code":"E707","names":"Penicillin G procaine","type":"antibiotic","status":""}],
  ["E708", {"code":"E708","names":"Penicillin G benzathine","type":"antibiotic","status":""}],
  ["E710", {"code":"E710","names":"Spiramycins","type":"antibiotic","status":""}],
  ["E711", {"code":"E711","names":"Virginiamycins","type":"antibiotic","status":""}],
  ["E712", {"code":"E712","names":"Flavomycin","type":"antibiotic","status":""}],
  ["E713", {"code":"E713","names":"Tylosin","type":"antibiotic","status":""}],
  ["E714", {"code":"E714","names":"Monensin A","type":"antibiotic","status":""}],
  ["E715", {"code":"E715","names":"Avoparcin","type":"antibiotic","status":""}],
  ["E716", {"code":"E716","names":"Salinomycin","type":"antibiotic","status":""}],
  ["E717", {"code":"E717","names":"Avilamycin","type":"antibiotic","status":""}],
  ["E900", {"code":"E900","names":"Dimethyl polysiloxane (anti-foaming agent)","type":"anti-caking agent","status":"e"}],
  ["E901", {"code":"E901","names":"Beeswax, white and yellow","type":"glazing agent","status":"e"}],
  ["E902", {"code":"E902","names":"Candelilla wax","type":"glazing agent","status":"e"}],
  ["E903", {"code":"E903","names":"Carnauba wax","type":"glazing agent","status":"e"}],
  ["E904", {"code":"E904","names":"Shellac","type":"glazing agent","status":"e"}],
  ["E905", {"code":"E905","names":"Paraffins","type":"","status":"e"}],
  ["E905a", {"code":"E905a","names":"Mineral oil","type":"anti-foaming agent","status":""}],
  ["E905b", {"code":"E905b","names":"Petrolatum","type":"","status":""}],
  ["E905c", {"code":"E905c","names":"Petroleum wax (i)Microcrystalline wax (ii) Paraffin wax","type":"glazing agent","status":""}],
  ["E906", {"code":"E906","names":"Gum benzoic","type":"flavour enhancer","status":""}],
  ["E907", {"code":"E907","names":"Crystalline wax","type":"glazing agent","status":""}],
  ["E908", {"code":"E908","names":"Rice bran wax","type":"glazing agent","status":""}],
  ["E909", {"code":"E909","names":"Spermaceti wax","type":"glazing agent","status":""}],
  ["E910", {"code":"E910","names":"Wax esters","type":"glazing agent","status":""}],
  ["E911", {"code":"E911","names":"Methyl esters of fatty acids","type":"glazing agent","status":""}],
  ["E912", {"code":"E912","names":"Montanic acid esters, Montan acid esters","type":"glazing agent","status":"e"}],
  ["E913", {"code":"E913","names":"Lanolin, sheep wool grease","type":"glazing agent","status":""}],
  ["E914", {"code":"E914","names":"Oxidized polyethylene wax, oxidized polyethylene","type":"glazing agent","status":"e"}],
  ["E915", {"code":"E915","names":"Esters of colophony","type":"glazing agent","status":""}],
  ["E916", {"code":"E916","names":"Calcium iodate","type":"","status":""}],
  ["E917", {"code":"E917","names":"Potassium iodate","type":"","status":""}],
  ["E918", {"code":"E918","names":"Nitrogen oxides","type":"","status":""}],
  ["E919", {"code":"E919","names":"Nitrosyl chloride","type":"","status":""}],
  ["E920", {"code":"E920","names":"L-cysteine","type":"improving agent","status":"e"}],
  ["E921", {"code":"E921","names":"L-cystine","type":"improving agent","status":""}],
  ["E922", {"code":"E922","names":"Potassium persulphate","type":"improving agent","status":""}],
  ["E923", {"code":"E923","names":"Ammonium persulphate","type":"improving agent","status":""}],
  ["E924", {"code":"E924","names":"Potassium bromate","type":"improving agent","status":""}],
  ["E924b", {"code":"E924b","names":"Calcium bromate","type":"improving agent","status":""}],
  ["E925", {"code":"E925","names":"Chlorine","type":"preservative, bleach, improving agent","status":""}],
  ["E926", {"code":"E926","names":"Chlorine dioxide (preservative)","type":"bleach","status":""}],
  ["E927a", {"code":"E927a","names":"Azodicarbonamide","type":"improving agent","status":""}],
  ["E927b", {"code":"E927b","names":"Carbamide (urea)","type":"improving agent","status":"e"}],
  ["E928", {"code":"E928","names":"Benzoyl peroxide (improving agent)","type":"bleach","status":""}],
  ["E929", {"code":"E929","names":"Acetone peroxide","type":"","status":""}],
  ["E930", {"code":"E930","names":"Calcium peroxide (improving agent)","type":"bleach","status":""}],
  ["E938", {"code":"E938","names":"Argon","type":"packaging gas","status":"e"}],
  ["E939", {"code":"E939","names":"Helium","type":"packaging gas","status":"e"}],
  ["E940", {"code":"E940","names":"Dichlorodifluoromethane","type":"packaging gas","status":""}],
  ["E941", {"code":"E941","names":"Nitrogen (packaging gas)","type":"propellant","status":"e"}],
  ["E942", {"code":"E942","names":"Nitrous oxide","type":"propellant","status":"e"}],
  ["E943a", {"code":"E943a","names":"Butane","type":"propellant","status":"e"}],
  ["E943b", {"code":"E943b","names":"Isobutane","type":"propellant","status":"e"}],
  ["E944", {"code":"E944","names":"Propane","type":"propellant","status":"e"}],
  ["E945", {"code":"E945","names":"Chloropentafluoroethane","type":"propellant","status":""}],
  ["E946", {"code":"E946","names":"Octafluorocyclobutane","type":"propellant","status":""}],
  ["E948", {"code":"E948","names":"Oxygen","type":"packaging gas","status":"e"}],
  ["E949", {"code":"E949","names":"Hydrogen","type":"packaging gas","status":"e"}],
  ["E950", {"code":"E950","names":"Acesulfame potassium","type":"sweetener","status":"e"}],
  ["E951", {"code":"E951","names":"Aspartame","type":"sweetener","status":"e"}],
  ["E952", {"code":"E952","names":"Cyclamic acid and its sodium and calcium salts, also known as Cyclamate","type":"sweetener","status":"e"}],
  ["E953", {"code":"E953","names":"Isomalt, Isomaltitol","type":"sweetener","status":"e"}],
  ["E954", {"code":"E954","names":"Saccharin and its sodium, potassium and calcium salts","type":"sweetener","status":"e"}],
  ["E955", {"code":"E955","names":"Sucralose (Trichlorogalactosucrose)","type":"sweetener","status":"e"}],
  ["E956", {"code":"E956","names":"Alitame","type":"sweetener","status":""}],
  ["E957", {"code":"E957","names":"Thaumatin (sweetener)","type":"flavour enhancer","status":"e"}],
  ["E958", {"code":"E958","names":"Glycyrrhizin (sweetener)","type":"flavour enhancer","status":""}],
  ["E959", {"code":"E959","names":"Neohesperidine dihydrochalcone (sweetener)","type":"flavour enhancer","status":"e"}],
  ["E960", {"code":"E960","names":"Steviol glycosides","type":"sweetener","status":"e"}],
  ["E961", {"code":"E961","names":"Neotame","type":"sweetener","status":"e"}],
  ["E962", {"code":"E962","names":"Aspartame-acesulfame salt (sweetener)","type":"stabiliser","status":"e"}],
  ["E965", {"code":"E965","names":"Maltitol (i) Maltitol (ii) Maltitol syrup (sweetener) (stabiliser)","type":"humectant","status":"e"}],
  ["E966", {"code":"E966","names":"Lactitol","type":"sweetener","status":"e"}],
  ["E967", {"code":"E967","names":"Xylitol","type":"sweetener","status":"e"}],
  ["E968", {"code":"E968","names":"Erythritol","type":"sweetener","status":"e"}],
  ["E999", {"code":"E999","names":"Quillaia extract","type":"foaming agent","status":"e"}],
  ["E1000", {"code":"E1000","names":"Cholic acid","type":"emulsifier","status":""}],
  ["E1001", {"code":"E1001","names":"Choline salts","type":"emulsifier","status":""}],
  ["E1100", {"code":"E1100","names":"Amylase","type":"stabiliser, flavour enhancer","status":""}],
  ["E1101", {"code":"E1101","names":"Proteases ((i)Protease, (ii)Papain, (iii)Bromelain, (iv)Ficin)","type":"stabiliser, flavour enhancer","status":""}],
  ["E1102", {"code":"E1102","names":"Glucose oxidase","type":"antioxidant","status":""}],
  ["E1103", {"code":"E1103","names":"Invertase","type":"stabiliser","status":"e"}],
  ["E1104", {"code":"E1104","names":"Lipases","type":"","status":""}],
  ["E1105", {"code":"E1105","names":"Lysozyme","type":"preservative","status":""}],
  ["E1200", {"code":"E1200","names":"Polydextrose","type":"stabiliser, thickening agent, humectant, carrier","status":"e"}],
  ["E1201", {"code":"E1201","names":"Polyvinylpyrrolidone","type":"stabiliser","status":"e"}],
  ["E1202", {"code":"E1202","names":"Polyvinylpolypyrrolidone (carrier)","type":"stabiliser","status":"e"}],
  ["E1203", {"code":"E1203","names":"Polyvinyl alcohol","type":"","status":"e"}],
  ["E1204", {"code":"E1204","names":"Pullulan","type":"","status":"e"}],
  ["E1400", {"code":"E1400","names":"Dextrin (Dextrins, roasted starch white and yellow) (stabiliser)","type":"thickening agent","status":""}],
  ["E1401", {"code":"E1401","names":"Modified starch ((Acid-treated starch) stabiliser)","type":"thickening agent","status":""}],
  ["E1402", {"code":"E1402","names":"Alkaline modified starch (stabiliser)","type":"thickening agent","status":""}],
  ["E1403", {"code":"E1403","names":"Bleached starch (stabiliser)","type":"thickening agent","status":""}],
  ["E1404", {"code":"E1404","names":"Oxidized starch (emulsifier)","type":"thickening agent","status":"e"}],
  ["E1405", {"code":"E1405","names":"Enzyme treated starch","type":"","status":""}],
  ["E1410", {"code":"E1410","names":"Monostarch phosphate (stabiliser)","type":"thickening agent","status":"e"}],
  ["E1411", {"code":"E1411","names":"Distarch glycerol (thickening agent)","type":"emulsifier","status":""}],
  ["E1412", {"code":"E1412","names":"Distarch phosphate esterified with sodium trimetasphosphate; esterified with phosphorus oxychloride (stabiliser)","type":"thickening agent","status":"e"}],
  ["E1413", {"code":"E1413","names":"Phosphated distarch phosphate (stabiliser)","type":"thickening agent","status":"e"}],
  ["E1414", {"code":"E1414","names":"Acetylated distarch phosphate (emulsifier)","type":"thickening agent","status":"e"}],
  ["E1420", {"code":"E1420","names":"Starch acetate esterified with acetic anhydride (stabiliser)","type":"thickening agent","status":"e"}],
  ["E1421", {"code":"E1421","names":"Starch acetate esterified with vinyl acetate (stabiliser)","type":"thickening agent","status":""}],
  ["E1422", {"code":"E1422","names":"Acetylated distarch adipate (stabiliser)","type":"thickening agent","status":"e"}],
  ["E1423", {"code":"E1423","names":"Acetylated distarch glycerol","type":"thickening agent","status":""}],
  ["E1430", {"code":"E1430","names":"Distarch glycerine (stabiliser)","type":"thickening agent","status":""}],
  ["E1440", {"code":"E1440","names":"Hydroxy propyl starch (emulsifier)","type":"thickening agent","status":"e"}],
  ["E1441", {"code":"E1441","names":"Hydroxy propyl distarch glycerine (stabiliser)","type":"thickening agent","status":""}],
  ["E1442", {"code":"E1442","names":"Hydroxy propyl distarch phosphate (stabiliser)","type":"thickening agent","status":"e"}],
  ["E1443", {"code":"E1443","names":"Hydroxy propyl distarch glycerol","type":"","status":""}],
  ["E1450", {"code":"E1450","names":"Starch sodium octenyl succinate (emulsifier) (stabiliser)","type":"thickening agent","status":"e"}],
  ["E1451", {"code":"E1451","names":"Acetylated oxidised starch (emulsifier)","type":"thickening agent","status":"e"}],
  ["E1452", {"code":"E1452","names":"Starch aluminium octenyl succinate","type":"","status":"e"}],
  ["E1501", {"code":"E1501","names":"Benzylated hydrocarbons","type":"","status":""}],
  ["E1502", {"code":"E1502","names":"Butane-1, 3-diol","type":"","status":""}],
  ["E1503", {"code":"E1503","names":"Castor oil","type":"resolving agent","status":""}],
  ["E1504", {"code":"E1504","names":"Ethyl acetate","type":"flavour solvent","status":""}],
  ["E1505", {"code":"E1505","names":"Triethyl citrate","type":"foam stabiliser","status":"e"}],
  ["E1510", {"code":"E1510","names":"Ethanol","type":"","status":""}],
  ["E1516", {"code":"E1516","names":"Glyceryl monoacetate","type":"flavour solvent","status":""}],
  ["E1517", {"code":"E1517","names":"Glyceryl diacetate or diacetin","type":"flavour solvent","status":""}],
  ["E1518", {"code":"E1518","names":"Glyceryl triacetate or triacetin","type":"humectant","status":"e"}],
  ["E1519", {"code":"E1519","names":"Benzyl alcohol","type":"","status":""}],
  ["E1520", {"code":"E1520","names":"Propylene glycol","type":"humectant","status":"e"}],
  ["E1521", {"code":"E1521","names":"Polyethylene glycol 8000[25]","type":"","status":"e"}],
  ["E1525", {"code":"E1525","names":"Hydroxyethyl cellulose","type":"thickening agent","status":""}],
]);
module.exports = CORPUS;
